const Joi = require('joi');

const W24TechreadAction = Object.freeze({
    INITIALIZE: "INITIALIZE",
    READ: "READ"
});

const W24TechreadMessageType = Object.freeze({
    ASK: "ASK",
    ERROR: "ERROR",  // Deprecated
    PROGRESS: "PROGRESS",
    REJECTION: "REJECTION"
});

const W24TechreadExceptionType = Object.freeze({
    DRAWING_FILE_FORMAT_UNSUPPORTED: "DRAWING_FILE_FORMAT_UNSUPPORTED",
    DRAWING_FILE_SIZE_TOO_LARGE: "DRAWING_FILE_SIZE_TOO_LARGE",
    DRAWING_RESOLUTION_TOO_LOW: "DRAWING_RESOLUTION_TOO_LOW",
    DRAWING_NOISE_TOO_HIGH: "DRAWING_NOISE_TOO_HIGH",
    DRAWING_CONTENT_NOT_UNDERSTOOD: "DRAWING_CONTENT_NOT_UNDERSTOOD",
    DRAWING_PAPER_SIZE_TOO_LARGE: "DRAWING_PAPER_SIZE_TOO_LARGE",
    DRAWING_MEASURE_SYSTEM_INCOMPLETE:"DRAWING_MEASURE_SYSTEM_INCOMPLETE",
    MODEL_FILE_FORMAT_UNSUPPORTED:"MODEL_FILE_FORMAT_UNSUPPORTED",
    MODEL_FILE_SIZE_TOO_LARGE: "MODEL_FILE_SIZE_TOO_LARGE",
    SUB_ACCOUNT_ACCESS_DENIED: "SUB_ACCOUNT_ACCESS_DENIED",
    SUB_ACCOUNT_NO_BALANCE: "SUB_ACCOUNT_NO_BALANCE"
});

let clientVersion  = require('../../package.json').version;


module.exports ={
    W24TechreadAction,
    W24TechreadMessageType,
    W24TechreadExceptionType,
}