# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    - name: Install the Python client
      run: pip install werk24==0.5.0rc1
        
    - name: Setup npm
      run: npm ci
      
    - name: Run the tests
      env:
        W24TECHREAD_AUTH_REGION: ${{ secrets.W24TECHREAD_AUTH_REGION }}
        W24TECHREAD_AUTH_IDENTITY_POOL_ID: ${{ secrets.W24TECHREAD_AUTH_IDENTITY_POOL_ID }}
        W24TECHREAD_AUTH_USER_POOL_ID: ${{ secrets.W24TECHREAD_AUTH_USER_POOL_ID }}
        W24TECHREAD_AUTH_CLIENT_ID: ${{ secrets.W24TECHREAD_AUTH_CLIENT_ID }}
        W24TECHREAD_AUTH_CLIENT_SECRET: ${{ secrets.W24TECHREAD_AUTH_CLIENT_SECRET }}
        W24TECHREAD_AUTH_USERNAME: ${{ secrets.W24TECHREAD_AUTH_USERNAME }}
        W24TECHREAD_AUTH_PASSWORD: ${{ secrets.W24TECHREAD_AUTH_PASSWORD }}
        W24TECHREAD_SERVER_HTTPS: ${{ secrets.W24TECHREAD_SERVER_HTTPS }}
        W24TECHREAD_SERVER_WSS: ${{ secrets.W24TECHREAD_SERVER_WSS }}
        W24TECHREAD_VERSION: ${{ secrets.W24TECHREAD_VERSION }}
      run: npm run itest
